### ISSUE TITLE
Cannot run the tests

### ISSUE THREAD

**Issue by JustalK** [Simperfy/Covid-19-API-Philippines-DOH#42]
**Describe the bug**
Hello po,

I have been trying to run your tests without success.

Once i clone your repository, I did that :
```
npm install
npm run test
```

And I am facing those errors : 

```
Please specify "DATABASE_TYPE" in environment variables

      28 |           msg = await this.connect(new MySQLDatabase());
      29 |         } else {
    > 30 |           throw new Error('Please specify "DATABASE_TYPE" in environment variables');
         |                 ^
      31 |         }
      32 |         console.log(msg);
      33 |       }

      at src/Database/DatabaseAdapter.js:30:17
      at new DatabaseAdapter (src/Database/DatabaseAdapter.js:18:12)
      at Object.<anonymous> (__tests__/src/Database/DatabaseAdapter.test.js:13:34)

```

And a second one : 

```
SyntaxError: /home/rumarocket/eclipse-workspace/Covid-19-API-Philippines-DOH/__tests__/src/DBLogger.test.js: Unexpected token, expected "," (60:24)

      58 | 
      59 | afterAll(() =>
    > 60 |   realDB.endConnection();
         |                         ^
      61 | });
```

After some research, I guess my error in inside the .env file.
However I dont see any information about it.
I see in the env file that there are fields for putting the credential of a mysql or nosql db. 
Does your application get the data from DOH and save them inside a db ?
I thought it was a reading directly from google drive ?

Thank you poa

**Comment by Simperfy** [comment]
> I see in the env file that there are fields for putting the credential of a mysql or nosql db.
It only uses mongoDB(NoSQL) db now, the mysql class is very outdated.

> Does your application get the data from DOH and save them inside a db?
Yes, it downloads the latest csv files, then sanitizes the data and then saves inside a mongo Database.

> I thought it was a reading directly from google drive ?
It is reading directly through google drive, it firsts goes to the [bit.ly/DataDropPH](bit.ly/DataDropPH) parses the pdf for the updated link of the google folder. If it's not found it uses the latest csv file from [archives](bit.ly/DataDropArchives) instead.

NOTE: There are some endpoints that do not have tests in master branch, but they will be covered in once I merge #38. I can't tell when I will finalize this PR, as I'm busy on an AI project.
